#!/bin/bash
swaylock --screenshots --indicator \
    --indicator-radius 100 \
    --indicator-thickness 7 \
    --effect-vignette 0.5:0.5 \
    --ring-color 0f111a \
    --key-hl-color 81A1C1 \
    --line-color 0f111a \
    --inside-color 0f111a \
    --separator-color 0f111a \
    --inside-ver-color 88C0D0 \
    --line-ver-color 88C0D0 \
    --ring-ver-color 88C0D0 \
    --inside-wrong-color BF616A \
    --line-wrong-color BF616A \
    --ring-wrong-color BF616A \
    --inside-clear-color EBCB8B \
    --line-clear-color EBCB8B \
    --ring-clear-color EBCB8B \
    --bs-hl-color B48EAD \
    --fade-in 0.3 \
    --effect-blur 5x8 \
    --font "Source Code Pro"
